### PR TITLE
Bring inline with pcgendev

### PR DESCRIPTION
**Pull request by karianna**

### CODE REVIEW

**Comment by thpr** [comment]
At first glance, this looks more permissive than the current rules (but also brings it up to the new version of PMD).  I will likely provide recommendations to reduce the exceptions

**Comment by LegacyKing** [comment]
@karianna - I'm seeing your merge commits in several PRs. When you pull from the master into your branch, please use the rebase option. It cleans up the commit to ignore those merges and makes for a cleaner PR.

**Comment by karianna** [comment]
Sure I may need some reminding from time to time :-)

**Comment by thpr** [comment]
Further investigation indicates the eclipse integration has not yet converted to PMD 6.0.  So I really don't think we should be using it yet until the tools catch up.

**Comment by LegacyKing** [comment]
Updates? @karianna @thpr

**Comment by karianna** [comment]
Hopefully the latest eclipse has caught this up.

**Comment by karianna** [comment]
Closing in favour of new PR

**Pull request closed without merging**
